# Generated by Django 3.1.4 on 2021-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('likes', models.CharField(default=1, max_length=10)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
