# Generated by Django 3.1.4 on 2021-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210122_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
